# Generated by Django 6.0.6 on 2026-07-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('risk_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
