# Generated by Django 6.0.6 on 2026-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('misinformation', 'Misinformation'), ('other', 'Other')], default='general', max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
    ]
